---
version: '3'
services:
  gemstash:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      RACK_ENV: production
      GEMSTASH_DB_ADAPTER: postgres
      GEMSTASH_DB_USERNAME: postgres
      GEMSTASH_DB_PASSWORD: sekretpassword
      GEMSTASH_DB_DATABASE: gemstash
      GEMSTASH_DB_HOST: postgres
      GEMSTASH_DB_PORT: 5432
      GEMSTASH_PUMA_THREADS: 4
    ports:
      - 9292:9292
    volumes:
      - gemstash_data:/home/gemstash/data
    links:
      - postgres
  postgres:
    image: postgres:14-alpine
    platform: linux/amd64
    volumes:
      - postgres_data:/usr/local/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=sekretpassword
      - POSTGRES_DB=gemstash

volumes:
  gemstash_data:
    driver: local
  postgres_data:
    driver: local
