---
version: '3'
services:
  gemstash:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      RACK_ENV: production
    ports:
      - 9292:9292
    volumes:
      - gemstash_data:/home/gemstash/data

volumes:
  gemstash_data:
    driver: local
