source 'https://rubygems.org'

ruby '3.2.2'

# Pg is the Ruby interface to the PostgreSQL.
gem 'pg', '~> 1.5'

# Gemstash acts as a local RubyGems server, caching copies of gems from
# RubyGems.org automatically, and eventually letting you push your own private
# gems as well.
gem 'gemstash', '~> 2.7'
